spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sicred
    username: postgres
    password: goku1515

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

server:
  port: 8080

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: design.boilerplate.springboot

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    design.boilerplate.springboot: INFO

jwt:
  secretKey: 2UtUnoOMjwNiTmeT2dLXNexH4vjAIyqTquvGCLdoEUcNY0F89P
  issuer: https://www.linkedin.com/in/gabriel-marques1989/
  expirationMinute: 10

swagger:
  contact-name: Gabriel Marques
  contact-mail: marques.gabriel.1989@gmail.com
  contact-url: https://www.linkedin.com/in/gabriel-marques1989/
  app-name: Spring Boot - Sicred Project
  app-description: "Projeto para entrega de teste técnico - Sidcred - Por Gabriel Marques"
  app-version: 2.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
