  @startuml

skinparam nodesep 120
skinparam ranksep 80

skinparam class {
BorderColor SpringGreen
}

note "Todas as entidades possuem uma chave burra\n (sequence / Long) como PK" as N1

entity Pauta {
  String Nome
}

entity Sessao {
  LocalDateTime Inicio
  LocalDateTime Fim
  Integer Tempo
  Pauta Pauta
}

entity Voto {
  Usuario Usuario
  VotoEnum Voto
  Sessao Sessao
  Pauta Pauta
}

enum VotoEnum{
  Sim
  Não
}

entity Usuario {
  String Nome
  String NomeDeUsuario
  String CPF
  String Email
  String Senha
}

Pauta "1" -- "0..*" Sessao
Sessao "1" -- "0..*" Voto
Usuario "1" -- "0..*" Voto

@enduml